version: "3.9"

services:
  simulador-api:
    build: .
    container_name: simuladorinvestimento-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/app/data
    environment:
      - QUARKUS_PROFILE=docker
    networks:
      - simulador-network

networks:
  simulador-network:
    driver: bridge
