# ===============================
# OPENAPI / SWAGGER
# ===============================
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.theme=flattop

# Health
quarkus.smallrye-health.root-path=/q/health


# ===============================
# LOGGING
# ===============================
quarkus.log.category."br.com.mattos.simuladorinvestimento".level=DEBUG

# ===============================
# JWT CONFIGURAÇÃO (HS256)
# ===============================

# Issuer do token (precisa bater com o token gerado)
mp.jwt.verify.issuer=meu-issuer

# Chave secreta para HS256 (mesma que no signWith)
mp.jwt.verify.signing.key=01234567890123456789012345678901

