# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS PARA DOCKER
# ===============================
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:/opt/app/data/simuladorteste27.db
quarkus.datasource.jdbc.driver=org.sqlite.JDBC

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Executa import.sql que está no classpath (src/main/resources)
quarkus.hibernate-orm.sql-load-script=import.sql

# Habilita execucao automatica de import.sql
#quarkus.hibernate-orm.sql-load-script=import.sql
