# ===============================
# OPENAPI / SWAGGER
# ===============================
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.theme=flattop

# Health
quarkus.smallrye-health.root-path=/q/health


# ===============================
# LOGGING OPCIONAL
# ===============================
quarkus.log.category."br.com.mattos.simuladorinvestimento".level=DEBUG

# ===============================
# JWT CONFIGURAÇÃO (HS256)
# ===============================

## Chave secreta HMAC (HS256)
##smallrye.jwt.sign.key=SIMULADOR_INVESTIMENTO_MATTOS_123456789
#smallrye.jwt.sign.key=U0lNVUxBRE9SX0lOVkVTVElNRU5UX01BVE9UU19fMTIzNDU2Nzg5
#smallrye.jwt.sign.key-location=none
#smallrye.jwt.sign.algorithm=HS256
## Verificação de token
#smallrye.jwt.verify.key=U0lNVUxBRE9SX0lOVkVTVElNRU5UX01BVE9UU19fMTIzNDU2Nzg5
#mp.jwt.verify.issuer=simulador-api


# Verificação de token
#smallrye.jwt.verify.key=SIMULADOR_INVESTIMENTO_MATTOS_123456789
#mp.jwt.verify.issuer=simulador-api

# ===============================
# LOGGING OPCIONAL
# ===============================
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
#quarkus.log.category."br.com.mattos.simuladorinvestimento".level=DEBUG
