# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS DOCKER
# ===============================
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:/opt/app/data/simuladorteste25.db
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Habilita execução automática de import.sql
quarkus.hibernate-orm.sql-load-script=import.sql
